#!/usr/bin/env bash
# Build a throwaway Go repository with a review-sized branch diff for the README demo
# (scripts/demo.tape). Go so that gopls attaches and the recording can show LSP hover
# working inside the diff views. Prints the repo path on stdout.
set -euo pipefail

dir="$(mktemp -d "${TMPDIR:-/tmp}/difit-demo.XXXXXX")"
cd "$dir"
git init -q -b main
git config user.name "difit demo"
git config user.email "demo@example.com"
git config commit.gpgsign false

cat > go.mod <<'EOF'
module example.com/parser

go 1.24
EOF
cat > parser.go <<'EOF'
package parser

// Parse splits the input into whitespace-separated tokens.
func Parse(input string) []string {
	tokens := []string{}
	current := ""
	for _, r := range input {
		if r == ' ' || r == '\n' || r == '\t' {
			if current != "" {
				tokens = append(tokens, current)
				current = ""
			}
			continue
		}
		current += string(r)
	}
	if current != "" {
		tokens = append(tokens, current)
	}
	return tokens
}
EOF
cat > render.go <<'EOF'
package parser

import "strings"

// Render joins tokens back into a single line.
func Render(tokens []string) string {
	return strings.Join(tokens, " ")
}
EOF
cat > config.go <<'EOF'
package parser

// MaxDepth bounds recursive parsing.
const MaxDepth = 3
EOF
git add -A
git commit -qm "init: parser skeleton"

git switch -qc feature/tokenizer
cat > token.go <<'EOF'
package parser

// Token is a classified fragment of the input.
type Token struct {
	Kind string
	Text string
}

// classify tags a fragment as a number or a word.
func classify(text string) string {
	for _, r := range text {
		if r < '0' || r > '9' {
			return "word"
		}
	}
	return "number"
}
EOF
cat > parser.go <<'EOF'
package parser

import "strings"

// Parse splits the input into classified tokens.
func Parse(input string) []Token {
	tokens := []Token{}
	for _, field := range strings.Fields(input) {
		tokens = append(tokens, Token{Kind: classify(field), Text: field})
	}
	return tokens
}
EOF
cat > render.go <<'EOF'
package parser

import "strings"

// Render joins tokens back into a single line.
func Render(tokens []Token) string {
	texts := make([]string, 0, len(tokens))
	for _, t := range tokens {
		texts = append(texts, t.Text)
	}
	return strings.Join(texts, " ")
}
EOF
cat > schema_gen.go <<'EOF'
// Code generated by scripts/gen.go. DO NOT EDIT.

package parser

var tokenKinds = []string{"word", "number"}
EOF
git rm -q config.go
git add -A
git commit -qm "feat: typed tokenizer"

echo "$dir"
