#!/usr/bin/env bash
# Build a throwaway git repository with a review-sized branch diff for the README
# demo (scripts/demo.tape). Prints the repo path on stdout.
set -euo pipefail

dir="$(mktemp -d "${TMPDIR:-/tmp}/difit-demo.XXXXXX")"
cd "$dir"
git init -q -b main
git config user.name "difit demo"
git config user.email "demo@example.com"
git config commit.gpgsign false

mkdir -p src/util config
cat > src/app.lua <<'EOF'
local parse = require("util.parse")
local format = require("util.format")

local M = {}

function M.run(input)
  local ast = parse.parse(input)
  return format.render(ast)
end

return M
EOF
cat > src/util/parse.lua <<'EOF'
local M = {}

function M.parse(input)
  local tokens = {}
  for word in input:gmatch("%S+") do
    table.insert(tokens, word)
  end
  return { kind = "doc", tokens = tokens }
end

return M
EOF
cat > src/util/format.lua <<'EOF'
local M = {}

function M.render(ast)
  return table.concat(ast.tokens, " ")
end

return M
EOF
cat > config/settings.lua <<'EOF'
return {
  max_depth = 3,
  strict = false,
}
EOF
cat > yarn.lock <<'EOF'
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
left-pad@^1.3.0:
  version "1.3.0"
EOF
git add -A
git commit -qm "init: parser skeleton"

git switch -qc feature/tokenizer
cat > src/util/tokenize.lua <<'EOF'
local M = {}

--- Split input into typed tokens instead of bare words.
function M.tokenize(input)
  local tokens = {}
  for word in input:gmatch("%S+") do
    local kind = word:match("^%d+$") and "number" or "word"
    table.insert(tokens, { kind = kind, text = word })
  end
  return tokens
end

return M
EOF
cat > src/util/parse.lua <<'EOF'
local tokenize = require("util.tokenize")

local M = {}

function M.parse(input)
  local tokens = tokenize.tokenize(input)
  return { kind = "doc", tokens = tokens }
end

return M
EOF
cat > src/app.lua <<'EOF'
local parse = require("util.parse")
local format = require("util.format")

local M = {}

function M.run(input)
  local ast = parse.parse(input)
  if #ast.tokens == 0 then
    return ""
  end
  return format.render(ast)
end

return M
EOF
mkdir -p gen
cat > gen/tokens_gen.lua <<'EOF'
-- Code generated by scripts/gen.lua. DO NOT EDIT.
return { "word", "number" }
EOF
cat > yarn.lock <<'EOF'
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
left-pad@^1.3.0:
  version "1.3.1"
EOF
git rm -q config/settings.lua
git add -A
git commit -qm "feat: typed tokenizer"

echo "$dir"
